### ISSUE TITLE
it's not work in nodebb 1.6.x or 1.7.x

### ISSUE THREAD

**Issue by Teddy-Zhu** [q8888620002/nodebb-plugin-elasticsearch#1]
i install the plugin ,but it's not work
1. the host setting is not work , it always connect localhost:27017
2. no topic or reply into es
can you fix it ? pls

**Comment by q8888620002** [comment]
Sorry for the late reply... Hope your issues have been solved. I believe that Nodebb supports Chinese text search with the lastest version.
